site_name: "PyLearn"
site_url: https://anzchy.github.io/pylearn
theme:
  name: material
  language: zh
  custom_dir: overrides
  features:
    - content.code.copy
    - navigation.tabs
  palette:
    primary: indigo
    accent: pink

nav:
  - 首页: index.md
  - 教程:
      - Python 基础: lessons/intro.md
      - Pandas 示例: lessons/pandas_demo.md
  - 开发指南: dev-guide.md
  - 部署指南: deployment.md

extra_css:
  - assets/style.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - md_in_html
  - pymdownx.superfences

plugins:
  - search
